### ISSUE TITLE
Add browser extensions support

### ISSUE THREAD

**Issue by 06wj** [06wj/shaderViewer#5]

**Comment by PrincessGod** [comment]
Integrate with some inspector?

https://github.com/benvanik/WebGL-Inspector
https://github.com/spite/ShaderEditorExtension

**Comment by 06wj** [comment]
@PrincessGod They seem to be not maintenance. 
I finished the [extensions](https://github.com/06wj/shaderViewer/blob/dev/extensions/extensions.crx?raw=true).
